### ISSUE TITLE
/usertraffic/json triggers exception

### ISSUE THREAD

**Issue by fgrsnau** [agdsn/sipa#150]
The url /usertraffic/json triggers the following exception:

    builtins.TypeError
    
    TypeError: 'str' object cannot be interpreted as an integer
    Traceback (most recent call last)

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)

    File "/home/sipa/sipa/sipa/initialization.py", line 196, in __call__
    return self.app(environ, start_response)

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()

    File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/sipa/sipa/sipa/blueprints/generic.py", line 208, in traffic_api
    trafficdata['quota'] = trafficdata.pop('credit')

    TypeError: 'str' object cannot be interpreted as an integer

**Comment by lukasjuhrich** [comment]
@fgrsnau Lovely someone finally tested this, I'm going to take care of the pull requests shortly!

**Comment by lukasjuhrich** [comment]
Oh, seems like I did not update this after refactoring `User.traffic_history`. :-1: for me.
