### ISSUE TITLE
Fix contact form

### ISSUE THREAD

**Issue by ibot3** [agdsn/sipa#401]
Submitting the contact form currently throws an HTTP 500 error.

**Comment by lukasjuhrich** [comment]
```
[2019-02-14 20:42:49,716] ERROR in app: Exception on /contact [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./sipa/blueprints/generic.py", line 271, in contact
    dormitory_name=form.dormitory.data,
  File "./sipa/mail.py", line 129, in send_contact_mail
    header={'Name': name, 'Dormitory': dormitory.display_name},
  File "./sipa/mail.py", line 203, in send_complex_mail
    message=compose_body(message, header=header),
  File "./sipa/mail.py", line 68, in send_mail
    sender = current_app.config['CONTACT_SENDER_MAIL']
KeyError: 'CONTACT_SENDER_MAIL'
```
Presumably not a bug.

**Comment by lukasjuhrich** [comment]
Setting the corresponding config entry fixed it.
