### ISSUE TITLE
gerok: ValueError on wrong login

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#66]
Trying to log in using the gerok division raises a `ValueError: No JSON object could be decoded`.

Trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/home/sipa/sipa/sipa/__init__.py", line 42, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sipa/sipa/sipa/blueprints/generic.py", line 115, in login
    user = User.authenticate(username, password)
  File "/home/sipa/sipa/model/gerok/user.py", line 69, in authenticate
    'pass': password})
  File "/home/sipa/sipa/model/gerok/user.py", line 165, in do_api_call
    return response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

`dump(response)` with context of the `return json.loads()` line yields (leaving unimportant data):

```
Details for requests.models.Response object at 0x7f954c277b10

<Response [200]>
__attrs__ ['_content', 'status_code', 'headers', 'url', 'history', 'encoding', 'reason', 'cookies',   ]
[…]
content 'NoAccount'
cookies […]
elapsed datetime.timedelta(0, 0, 305231)
encoding 'utf-8'
headers […]
history []
is_permanent_redirect False
is_redirect False
iter_content <bound method Response.iter_content of <Response [200]>>
iter_lines <bound method Response.iter_lines of <Response [200]>>
json <bound method Response.json of <Response [200]>>
links {}
ok True
raise_for_status <bound method Response.raise_for_status of <Response [200]>>
raw <requests.packages.urllib3.response.HTTPResponse object at 0x7f954c277b90>
reason 'OK'
request <PreparedRequest [POST]>
status_code 200
text u'NoAccount'
url u'https://172.17.42.1:3000/api/auth'
```

I believe this can be resolved using a simple if statement checking the status.

**Comment by lukasjuhrich** [comment]
Addition: This occurs **only** if the account does not exist, **not** if the password is wrong!
